
name: wf-develop-pr
on:
  pull_request:
    branches:
      - develop
jobs:
  wf-develop-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "welcome to linting job"
      - name: repo checkout
        uses: actions/checkout@v4
      - name: install HTMLHINT
        run: npm install --save-dev htmlhintrc
      - name: install stylelint
        run: npm install --save-dev stylelintrc
      - name: Lint Html files
        run: npx htmlhint "**/*.html"
      - name: Lint CSS files
        run: npx stylelint "**/*.css"
      - name: Build website using Parcel
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
      - name: Display package.json contents
        run: |
          cat package.json
